export default class STYLE_CONFIGURATION {
  public static readonly TAB_BAR_HEIGHT: number = 48
  // 页签高度
  public static readonly ICON_SIZE: number = 16
  // 图标尺寸
  public static readonly TAB_BAR_CONTENT_GUTTER: number = 6
  // 页签内元素间距
  public static readonly TAB_BAR_ITEM_GUTTER: number = 6
  // 页签间距
  public static readonly SEPARATOR_STROKE_WIDTH: number = 2
  // 分割线宽度
  public static readonly CONTENT_GUTTER_M: number = 12
  // 元素间距
  public static readonly CONTENT_GUTTER_S: number = 8
  // 元素间距
  public static readonly GRID_HEIGHT: number = 170
  // 快捷方式高度
  public static readonly GRID_MARGIN: number = 48
  // 快捷方式外边距
  public static readonly TAB_SHEET_PADDING: number = 6
  // 页签内边距
  public static readonly IMAGE_SIZE: number = 56
  // 图片尺寸
  public static readonly IMAGE_RADIUS: number = 32
  // 图片圆角
  public static readonly TEXT_HEIGHT: number = 12
  // 文本高度
  public static readonly TEXT_WIDTH: number = 48
  // 文本宽度
  public static readonly SEARCH_HEIGHT: number = 28
  // 工具栏搜索框高度
  public static readonly BIG_ICON_SIZE: number = 30
  // 添加和删除按钮的尺寸
  public static readonly BIG_ICON_PADDING: number = 7
  // 添加和删除按钮的padding值
}