/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ProductDataModel } from '../model/GoodsModel'

// 商品列表数据源
export const PRODUCT_DATA: Array<ProductDataModel> = [
  new ProductDataModel(0, $r("app.media.fit_for_dark_mode_product00"), "充电宝", "￥79.9", "1.0W"),
  new ProductDataModel(1, $r("app.media.fit_for_dark_mode_product01"), "笔记本电脑", "￥6979.9", "9.8k"),
  new ProductDataModel(2, $r("app.media.fit_for_dark_mode_product02"), "移动手机", "￥4279.9", "1.2k"),
  new ProductDataModel(3, $r("app.media.fit_for_dark_mode_product03"), "电动按摩椅", "￥5385.9", "899"),
  new ProductDataModel(4, $r("app.media.fit_for_dark_mode_product04"), "折叠屏", "￥1252.9", "4.2W"),
  new ProductDataModel(5, $r("app.media.fit_for_dark_mode_product05"), "极简潮流背包", "￥105.9", "1.2W"),
  new ProductDataModel(6, $r("app.media.fit_for_dark_mode_product00"), "充电宝", "￥79.9", "1.0W"),
  new ProductDataModel(7, $r("app.media.fit_for_dark_mode_product01"), "笔记本电脑", "￥6979.9", "9.8k"),
  new ProductDataModel(8, $r("app.media.fit_for_dark_mode_product02"), "移动手机", "￥4279.9", "1.2k"),
  new ProductDataModel(9, $r("app.media.fit_for_dark_mode_product03"), "电动按摩椅", "￥5385.9", "899"),
  new ProductDataModel(10, $r("app.media.fit_for_dark_mode_product04"), "折叠屏", "￥1252.9", "4.2W"),
  new ProductDataModel(11, $r("app.media.fit_for_dark_mode_product05"), "极简潮流背包", "￥105.9", "1.2W")
];