export class Constants {
  static readonly VIBRATION_TIME: number = 600
  static readonly ANIMATION_TIME: number = 600
  static readonly MARGIN_VERTICAL: number = 16
  static readonly FLEX_SHRINK: number = 1
  static readonly POPUP_POSITION_X: number = 8
  static readonly POPUP_POSITION_Y: number = 1
  static readonly MARK_POSITION_X: number = 4
  static readonly MARK_POSITION_Y: number = 9
  static readonly POSITION_ZERO: number = 0
  static readonly OPACITY_VALUE: number = 0.8
  static readonly PLAYBACK_COUNT: number = 2
  static readonly TRANSLATE_OFFSET_X: number = 5
}